name: Build DevBuild
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/build.yml
      - src/**
      - browser/**
      - scripts/build/**
      - package.json
      - pnpm-lock.yaml
env:
  FORCE_COLOR: true

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2 # Install pnpm using packageManager key in package.json

      - name: Use Node.js 19
        uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build web
        run: pnpm buildWeb --standalone

      - name: Build
        run: pnpm build --standalone

      - name: Generate plugin list
        run: pnpm generatePluginJson dist/plugins.json dist/plugin-readmes.json

      - name: Clean up obsolete files
        run: |
          rm -rf dist/*-unpacked dist/monaco Vencord.user.css vencordDesktopRenderer.css vencordDesktopRenderer.css.map

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: devbuild
          release_name: DevBuild ${{ github.sha }}
          draft: false
          prerelease: false

      - name: Upload release assets
        id: upload-release-assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/
          asset_name: devbuild.zip
          asset_content_type: application/zip
